# Generated by Django 2.2.1 on 2019-05-20 04:05

import apps.trades.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.CharField(default=apps.trades.models._trade_pk, editable=False, help_text='Auto-generated unique trade identifier.', max_length=9, primary_key=True, serialize=False)),
                ('sell_currency', models.CharField(choices=[('ARS', 'ARS'), ('EUR', 'EUR'), ('USD', 'USD')], help_text='Currency to sell.', max_length=3)),
                ('sell_amount', models.DecimalField(decimal_places=2, help_text='Amount to sell.', max_digits=1026)),
                ('buy_currency', models.CharField(choices=[('ARS', 'ARS'), ('EUR', 'EUR'), ('USD', 'USD')], help_text='Currency to buy.', max_length=3)),
                ('buy_amount', models.DecimalField(decimal_places=2, editable=False, help_text='Amount to buy.', max_digits=1026)),
                ('rate', models.DecimalField(decimal_places=6, editable=False, help_text='Calculated rate at the time of transaction.', max_digits=1030)),
                ('date_booked', models.DateTimeField(auto_now_add=True, help_text='Timestamp of the transaction.')),
            ],
        ),
    ]
